name: bubbles
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  supabase_flutter: ^2.8.1
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  mobile_scanner: ^5.2.3
  flutter_markdown: ^0.7.4
  intl: ^0.19.0
  record: ^6.1.2
  url_launcher: ^6.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo_light.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/text/