name: bubbles
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  permission_handler: ^11.3.1
  supabase_flutter: ^2.6.0
  image_picker: ^1.1.2
  mobile_scanner: ^7.1.3
  record: ^6.1.2
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo_light.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/text/